# Generated by Django 3.0.7 on 2020-06-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
    ]
