# Generated by Django 3.0.7 on 2020-06-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
